name: release-docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.29.2 --activate

      - name: Install and Build
        run: |
          pnpm install
          pnpm docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: dist-docs
